### ISSUE TITLE
Tag release for initial compliant kubernetes

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/k8s-compliant-kubernetes#16]
@GINAGC commented on [Fri Apr 16 2021](https://github.com/k8-proxy/cs-k8s-api/issues/74)

Please tag release for initial compliant kubernetes:
- management UI
- OVA workflow
- other fixes.

**Comment by gurunathg** [comment]
https://github.com/k8-proxy/k8s-compliant-kubernetes/releases/tag/Ck8_GWCloudSDK_V_1.0
