### ISSUE TITLE
Update on OVA/AMI workflow to secure secrets

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/k8s-compliant-kubernetes#18]
We need to create a secure version of the process for the secrets creation.

**Comment by gurunathg** [comment]
Pipeline will be modified to prevent display of secrets. Approach in mind and will be implementing it

**Comment by GINAGC** [comment]
@gurunathg we need to review this with Infosec team and this needs to be approved before implementing please.

**Comment by GINAGC** [comment]
Infosec approved to follow the recommendation from Nader:

 I recommend that we use AWS CLI to upload secrets.yaml to a private s3 bucket with with every run.
So the process would be we don't print the secrets in the logs and instead we use command
aws s3 cp "secrets.yaml-<RunNumber>" s3://<PrivateBucket>
which will print in the logs
uploaded: ./sercrets.taml to s3://<PrivateBucket>/secrets.yaml
and then the file can be downloaded easily from local before setting cloudformation or whatever using one command and surely after setting aws keys
aws s3 cp s3://<PrivateBucket>/secrets.yaml ./

**Comment by naderaly** [comment]
@GINAGC This is now fixed with this PR
https://github.com/k8-proxy/k8s-compliant-kubernetes/pull/27

**Comment by GINAGC** [comment]
@naderaly thank you, please update documentation here: https://github.com/k8-proxy/cs-k8s-api/blob/main/deployment.md on how credentials will be stored, add one example and remove old information. Thanks!
