### ISSUE TITLE
Test OVAs and update documentation as final deliverable

### ISSUE THREAD

**Issue by kekesimarti** [k8-proxy/k8s-compliant-kubernetes#25]

**Comment by naderaly** [comment]
@kekesimarti can U please share latest OVAs links ?

**Comment by kekesimarti** [comment]
@GINAGC do you have the OVA links?

**Comment by naderaly** [comment]
@GINAGC sure, please let us know when ready. Thank you

**Comment by GINAGC** [comment]
@naderaly 

OVAs are ready here: https://github.com/k8-proxy/k8s-compliant-kubernetes/runs/2475395680?check_suite_focus=true

The goal is to test the deployment on ESXi and update this documentation: https://github.com/k8-proxy/cs-k8s-api/blob/main/Integration/Filedrop.md (to be more detailed as the one for AWS for example: https://github.com/k8-proxy/cs-k8s-api/blob/main/Integration/Filedrop_AWS.md)

Also, I would like that you do another review on service cluster and improve the documentation as needed. 

After your review, we can pass the same to Jurgen for one more review. Thanks

**Comment by Lestat06** [comment]
Thank you @GINAGC . I wont start it this yet then and will be in touch with @naderaly

**Comment by naderaly** [comment]
Hello @GINAGC @Lestat06 , I have tested both OVAs and theybare working fine.
I just have couple of comments:
For the workload OVA I didnt find the required .txt files or the bash script to integrate with service cluster so I needed to create/download it which is not the best practice also I remember @gurunathg said they should be already in user's home  directory.
For the service OVA: the wizard script that help updating IP address and password is not included in the OVA. Which is needed as the client will need to assign a new IP dor the vm once deployed.

**Comment by naderaly** [comment]
I will work on improving the documentation now

**Comment by GINAGC** [comment]
Thank you @naderaly, I have posted this on the channel. Could you please improve the documentation above for OVA?

**Comment by naderaly** [comment]
@GINAGC PR for the OVA deployment improvement as well as detailed information for the integration between the service cluster and the worker cluster including the passwords extraction from the secrets file on s3 according to our agreement with Chris Holman  https://github.com/k8-proxy/cs-k8s-api/pull/134

**Comment by GINAGC** [comment]
@Lestat06 you can know the take the OVAs from here: https://github.com/k8-proxy/k8s-compliant-kubernetes/runs/2528083144?check_suite_focus=true

Please follow documentation https://github.com/naderaly/cs-k8s-api/blob/4775d7b3a6162d440252d5ebcef5c1b7b6853ed3/Integration/Esxi-deployment.md and update/improve as needed.

@naderaly I only see documentation to extract passwords for OVA, is the same process for AMI? Please remove that documentation from here: https://github.com/naderaly/cs-k8s-api/blob/4775d7b3a6162d440252d5ebcef5c1b7b6853ed3/Integration/Esxi-deployment.md#extracting-passwords and create a new MD with those instructions for OVA and AMI here: https://github.com/k8-proxy/cs-k8s-api/tree/main/Integration

**Comment by Lestat06** [comment]
@GINAGC The deployment was ok. beside some minor issue which we fixed with Gurunath. We will check if we can add a troubleshooting section for that or if it was a one time thing. Other than that OVSs are working fine

-added minor fixes in doc
-removed the manual download of /home/ubuntu/wc-coredns-configmap.yml since its downloaded automatically when u run setupscCluster.sh from documentation

PR: https://github.com/k8-proxy/cs-k8s-api/pull/153

**Comment by Lestat06** [comment]
> `service-cluster-ip.txt , monitoring-password.txt , logging-password.txt , cluster.txt ` have to be manually configured every time as they aren't static values.
> for the rest 3 files and added an echo command in the documentation for convince

@naderaly ok didn't know that. we will have to add that in the documentation with placeholders for those 4 files.
the editing/creation of those files is mentioned in the documentation only in the scenario if they are missing altogether
FYI @GINAGC

**Comment by GINAGC** [comment]
@Lestat06 yes, please update the documentation with the above.

**Comment by Lestat06** [comment]
@GINAGC PR with the above changes  https://github.com/k8-proxy/cs-k8s-api/pull/162. could not link PR to the issue. maybe because i dont have access to repo

**Comment by dtollaku** [comment]
@Lestat06 I gave you access to the repo

**Comment by GINAGC** [comment]
Thanks @Lestat06 

Please create separate MD file for the extract credentials section: https://github.com/Lestat06/cs-k8s-api/blob/0be2ae1e07e70629c5bf768978ee6a94a4bbaca8/Integration/Esxi-deployment.md#extracting-passwords 

- are these steps the same for AWS? if yes, please update accordingly 
- please add as a pre-requisite to know the URL/ID of the workflow run 

After this, I will send to Shereen to update documentation on wiki too.

**Comment by Lestat06** [comment]
> @Lestat06 I gave you access to the repo

@dtollaku can u give me access for this one too pls? 
https://github.com/k8-proxy/cs-k8s-api

**Comment by dtollaku** [comment]
done

**Comment by Lestat06** [comment]
@GINAGC Please review PR https://github.com/k8-proxy/cs-k8s-api/pull/168 
- added password exctration MD
- synched AWS and ESXi integration
- added pre-req

**Comment by Lestat06** [comment]
@GINAGC can u review this PR https://github.com/k8-proxy/cs-k8s-api/pull/180
fixed broken links that redirect to PW_EXTRACTION.md
