### ISSUE TITLE
Improvements needed in OVA GW Cloud SDK / Compliant kubernetes

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/k8s-compliant-kubernetes#28]
Please review these 2 comments:
- For the workload OVA I didnt find the required .txt files or the bash script to integrate with service cluster so I needed to create/download it which is not the best practice also I remember @gurunathg said they should be already in user’s home directory.
- For the service OVA: the wizard script that help updating IP address and password is not included in the OVA. Which is needed as the client will need to assign a new IP dor the vm once deployed.
-  the wizard needs some improvements also, as the way it works that it deletes all the files under /etc/netplan and generate a new one which works for the first time when the OVA is deployed but when the VM is restarted or shutdown/up the pods internal networking is missed up as the wizard script has deleted 20-internal-network.yaml file

**Comment by gurunathg** [comment]
Fixed missing .txt files required for integration. Working with @naderaly for new wizard script

**Comment by gurunathg** [comment]
Completed changes and created a run: https://github.com/k8-proxy/k8s-compliant-kubernetes/actions/runs/816888442

**Comment by GINAGC** [comment]
@naderaly can you test these OVAs and confirm if issues are fixed?

**Comment by naderaly** [comment]
@GINAGC I have tested the latest OVAs from this run https://github.com/k8-proxy/k8s-compliant-kubernetes/runs/2528083144?check_suite_focus=true
and all the mentioned above points were resolved

**Comment by GINAGC** [comment]
Great, thank you!

**Comment by gurunathg** [comment]
@naderaly Thanks for testing and confirming changes. I will be merging these changes to ck8-filedrop version
