### ISSUE TITLE
CI for GW Cloud SDK withcompliant kubernetes

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/k8s-compliant-kubernetes#3]
1.- Update CI on compliant kuberenetes version so we have a workflow for: OVA/AMI of GW Cloud SDK with compliant kubernetes: https://github.com/k8-proxy/k8s-compliant-kubernetes/actions

**Comment by gurunathg** [comment]
Added CI pipeline to create AMI with GW CloudSDK
https://github.com/k8-proxy/k8s-compliant-kubernetes/pull/13
