### ISSUE TITLE
Logs sources and kubernetes commands for troubleshotting 

### ISSUE THREAD

**Issue by kekesimarti** [k8-proxy/k8s-compliant-kubernetes#36]
- Document how to take ID and find the reason of why it failed
- document the paths and how to access different log sources to monitor a worker cluster and the most used kubernetes commands for troubleshooting. Please confirm if you can take this.

**Comment by naderaly** [comment]
Hello @kekesimarti can I have more details what's exactly needed here so we can close this issue ?

**Comment by GINAGC** [comment]
@naderaly this is to document the paths and how to access different log sources to monitor a worker cluster and the most used kubernetes commands for troubleshooting. Please confirm if you can take this.

**Comment by naderaly** [comment]
Accessing pods logs and replacing corrupted pod as a troubleshooting step documented here https://github.com/k8-proxy/k8s-compliant-kubernetes/blob/ck8-main/troubleshoot.md

**Comment by naderaly** [comment]
working on documenting how to trace logs for specific rebuilt file

**Comment by GINAGC** [comment]
@gurunathg, @pranaysahith please see the link above from Nader. Anything else that we should add?

**Comment by gurunathg** [comment]
Steps to Identify reason of rebuilt failure:
1. Login to Kibana and navigate to Kubernetes index
2. Search "`GW_FAILED`" in required time range
In message field, we can find id of file...something like: `Returning 'GW_FAILED' Outcome for f9e0dc38-0a00-4a8e-93e9-b3e055d1836e`
3. Copy the id and search using id "`f9e0dc38-0a00-4a8e-93e9-b3e055d1836e`"
4. Focus on `message ` filed of logs with fileid 
5.  One can find reason of failure of rebuilt. e.g., `Filetype Detected: Unknown`

**Comment by GINAGC** [comment]
@svf97 please take the comment from Gurunath and the documentation from Nader and add another section under compliant kubernetes please.

**Comment by svf97** [comment]
@GINAGC this is done https://k8-proxy.github.io/k8-proxy-documentation/docs/products/compliant%20kubernetes/troubleshooting

**Comment by GINAGC** [comment]
Thank you, closing.
