### ISSUE TITLE
Deep analysis of Compliant Kubernetes

### ISSUE THREAD

**Issue by kekesimarti** [k8-proxy/k8s-compliant-kubernetes#38]
- Analyze the advantage of compliant Kubernetes, what works, what we already have, capture what exists today, document it.
- Document which components we have in the current implementation.
- After the above is documented, do a release to have a baseline: We need to get very quickly to a baseline of deployment of this, so we can understand what are the implications on both sides of the environment, on the performance

**Comment by naderaly** [comment]
This is documented here: https://docs.google.com/document/d/1nwbpUshzy18pKYH_kYmwoMtfxC0_mg2eQOPTA4QzDJ4/edit
