### ISSUE TITLE
Define the capabilities that are missing and each of those should be added like a development pipeline.

### ISSUE THREAD

**Issue by kekesimarti** [k8-proxy/k8s-compliant-kubernetes#39]
- Make a list of what we need to add. authentication, backup, etc. (This to be reviewed with the stakeholders once it is documented).
- Especially interesting in login and security features

**Comment by naderaly** [comment]
supported features and missing features are documented here 
https://docs.google.com/document/d/1nwbpUshzy18pKYH_kYmwoMtfxC0_mg2eQOPTA4QzDJ4/edit

**Comment by GINAGC** [comment]
@svf97 please create a new section called Compliant Kubernetes: https://k8-proxy.github.io/k8-proxy-documentation/docs/products/a-main with 1 page for now.

That page should contain:
1.- Quick overview and link to https://compliantkubernetes.io/
2.- Section "Glasswall ICAP Adaptation Service on Compliant Kubernetes" from the document from Nader.
3.- Quick links to the compliant kubernetes website for the topics in Naders document. For example, for all the topics and subtopics. 

Thank you

**Comment by GINAGC** [comment]
Hi @svf97 from this we are missing, the point 3, which are the main sections from the documentation links to the compliant kubernetes website.
