### ISSUE TITLE
 Understand data lost when a worker cluster is deleted.

### ISSUE THREAD

**Issue by kekesimarti** [k8-proxy/k8s-compliant-kubernetes#40]
- Include in the architecture that we don't need to backup and restore the cluster because we just start a new one.
- if the servers go offline, do we lose data?
- Understand and document the data impact when removing a worker cluster, do we lost any data? what keeps stored in the service cluster?

**Comment by naderaly** [comment]
By default all logs & metrics are collected from running worker cluster and stored in service cluster so deleting a worker cluster doesn't cause data lose.
If for some reason the worker cluster can't communicate/reach the service cluster the logs are temporary saved on the worker cluster (configurable amount of GB) until the service cluster is back online
For more info: https://docs.google.com/document/d/1nwbpUshzy18pKYH_kYmwoMtfxC0_mg2eQOPTA4QzDJ4/edit

**Comment by GINAGC** [comment]
@svf97 please also add this to the documentation that you will create. Add a specific section explaining this.

**Comment by GINAGC** [comment]
@svf97 also update on this one please.

**Comment by svf97** [comment]
@GINAGC 
compliant kubernetes doc: https://k8-proxy.github.io/k8-proxy-documentation/docs/products/compliant%20kubernetes/overview
troubleshooting: https://k8-proxy.github.io/k8-proxy-documentation/docs/products/compliant%20kubernetes/troubleshooting

**Comment by GINAGC** [comment]
@svf97 I cannot find the part that Nader mentioned on this issue in the documentation. Please review.

**Comment by svf97** [comment]
@GINAGC https://k8-proxy.github.io/k8-proxy-documentation/docs/products/compliant%20kubernetes/troubleshooting

**Comment by GINAGC** [comment]
Thank you, closing.
