### ISSUE TITLE
Capture the IP address of who made the request and show it in the logs

### ISSUE THREAD

**Issue by kekesimarti** [k8-proxy/k8s-compliant-kubernetes#50]

**Comment by GINAGC** [comment]
@pranaysahith are you working on this?

**Comment by pranaysahith** [comment]
yes @GINAGC

**Comment by GINAGC** [comment]
@svf97 please review this one with Pranay and add to the documentation you are working on.

**Comment by GINAGC** [comment]
@svf97 is there any update on this task?

**Comment by svf97** [comment]
@GINAGC 
yes, https://k8-proxy.github.io/k8-proxy-documentation/docs/products/compliant%20kubernetes/p-monitoring

**Comment by GINAGC** [comment]
1.
