### ISSUE TITLE
Update CI/CD pipelines to build develop and main branches 

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/k8s-compliant-kubernetes#58]
Updates made on CI/CD pipeline:

- Build AMI/OVA with eval SDK in non main branch including develop.
- Build AMI/OVA with eval and prod SDK in main branch
- Make eval AMI/OVA public by default
- Add SDK version as tag on AMI/OVA

**Comment by GINAGC** [comment]
@Lestat06 is this fully tested?

**Comment by Lestat06** [comment]
@GINAGC is this the same I have here with Shereen?
https://github.com/k8-proxy/GW-proxy/issues/392

**Comment by GINAGC** [comment]
yes @Lestat06, I am closing this one as duplicate. Thank you
