### ISSUE TITLE
Review Snyc detected vulnerabilities for k8s-compliant-kubernetes

### ISSUE THREAD

**Issue by kekesimarti** [k8-proxy/k8s-compliant-kubernetes#59]
1. Get access to Snyc
2. For the repository assigned, do an analysis of the vulnerabilities detected.
3. Confirm if any of the vulnerabilities can quickly solved.
4. Confirm from development perspective which vulnerabilities could have high impact in product.
5. Any additional information on the analysis.

**Comment by GINAGC** [comment]
@gurunathg can you please add a summay of the updates made so far?

**Comment by gurunathg** [comment]
After modification of PSP to prevent running as root, all pods are failing:
```

root@ip-172-31-31-63:/home/ubuntu# kubectl get pods -n icap-adaptation
NAME                                                   READY   STATUS                       RESTARTS   AGE
adaptation-icap-adaptation-event-api-699464789-npj5j   0/1     CreateContainerConfigError   0          17h
```

`Warning  Failed     17h (x7 over 17h)  kubelet            Error: container has runAsNonRoot and image will run as root`

All the images used by ICAP service are to be updated to run as non-root.

**Comment by gurunathg** [comment]
Dependency: All docker images are to be updated to run as non root
